-- MySQL Script generated by MySQL Workbench
-- Sun Jul 10 19:26:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestion_pedidos_poderes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestion_pedidos_poderes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion_pedidos_poderes` DEFAULT CHARACTER SET utf8 ;
USE `gestion_pedidos_poderes` ;

-- -----------------------------------------------------
-- Table `gestion_pedidos_poderes`.`tb_poder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_pedidos_poderes`.`tb_poder` ;

CREATE TABLE IF NOT EXISTS `gestion_pedidos_poderes`.`tb_poder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `duracion` INT(11) NOT NULL,
  `imagen` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_pedidos_poderes`.`tb_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_pedidos_poderes`.`tb_cliente` ;

CREATE TABLE IF NOT EXISTS `gestion_pedidos_poderes`.`tb_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `documento` INT NOT NULL,
  `tipodocumento` INT(2) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NULL,
  `direccion` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `celular` INT(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_pedidos_poderes`.`tb_carritocompra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_pedidos_poderes`.`tb_carritocompra` ;

CREATE TABLE IF NOT EXISTS `gestion_pedidos_poderes`.`tb_carritocompra` (
  `id` INT NOT NULL,
  `fechacreacion` DATETIME NULL,
  `tb_cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_carritocompra_tb_cliente1_idx` (`tb_cliente_id` ASC),
  CONSTRAINT `fk_tb_carritocompra_tb_cliente1`
    FOREIGN KEY (`tb_cliente_id`)
    REFERENCES `gestion_pedidos_poderes`.`tb_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_pedidos_poderes`.`tb_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_pedidos_poderes`.`tb_pedido` ;

CREATE TABLE IF NOT EXISTS `gestion_pedidos_poderes`.`tb_pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `estado` VARCHAR(10) NULL,
  `tb_cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_pedido_tb_cliente1_idx` (`tb_cliente_id` ASC) ,
  CONSTRAINT `fk_tb_pedido_tb_cliente1`
    FOREIGN KEY (`tb_cliente_id`)
    REFERENCES `gestion_pedidos_poderes`.`tb_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_pedidos_poderes`.`tb_pedidopoder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_pedidos_poderes`.`tb_pedidopoder` ;

CREATE TABLE IF NOT EXISTS `gestion_pedidos_poderes`.`tb_pedidopoder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tb_pedido_id` INT NOT NULL,
  `tb_poder_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_pedidocliente_tb_pedido1_idx` (`tb_pedido_id` ASC) ,
  INDEX `fk_tb_pedidocliente_tb_poder1_idx` (`tb_poder_id` ASC) ,
  CONSTRAINT `fk_tb_pedidocliente_tb_pedido1`
    FOREIGN KEY (`tb_pedido_id`)
    REFERENCES `gestion_pedidos_poderes`.`tb_pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedidocliente_tb_poder1`
    FOREIGN KEY (`tb_poder_id`)
    REFERENCES `gestion_pedidos_poderes`.`tb_poder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_pedidos_poderes`.`tb_carritopoder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_pedidos_poderes`.`tb_carritopoder` ;

CREATE TABLE IF NOT EXISTS `gestion_pedidos_poderes`.`tb_carritopoder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tb_carritocompra_id` INT NOT NULL,
  `tb_poder_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_carritocliente_tb_poder1_idx` (`tb_poder_id` ASC) ,
  INDEX `fk_tb_carritocliente_tb_carritocompra1_idx` (`tb_carritocompra_id` ASC) ,
  CONSTRAINT `fk_tb_carritocliente_tb_poder1`
    FOREIGN KEY (`tb_poder_id`)
    REFERENCES `gestion_pedidos_poderes`.`tb_poder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_carritocliente_tb_carritocompra1`
    FOREIGN KEY (`tb_carritocompra_id`)
    REFERENCES `gestion_pedidos_poderes`.`tb_carritocompra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_pedidos_poderes`.`tb_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_pedidos_poderes`.`tb_pago` ;

CREATE TABLE IF NOT EXISTS `gestion_pedidos_poderes`.`tb_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `modopago` VARCHAR(55) NULL,
  `tb_pedido_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_pago_tb_pedido1_idx` (`tb_pedido_id` ASC) ,
  CONSTRAINT `fk_tb_pago_tb_pedido1`
    FOREIGN KEY (`tb_pedido_id`)
    REFERENCES `gestion_pedidos_poderes`.`tb_pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_pedidos_poderes`.`tb_envio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_pedidos_poderes`.`tb_envio` ;

CREATE TABLE IF NOT EXISTS `gestion_pedidos_poderes`.`tb_envio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(100) NOT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `fechaenvio` DATETIME NOT NULL,
  `empresamensajeria` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `tb_pedido_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_envio_tb_pedido1_idx` (`tb_pedido_id` ASC) ,
  CONSTRAINT `fk_tb_envio_tb_pedido1`
    FOREIGN KEY (`tb_pedido_id`)
    REFERENCES `gestion_pedidos_poderes`.`tb_pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
